# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np
array = np.arange(10)
array = np.arange(10).reshape(2,5)
array


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [29]:
import numpy as np
a = np.arange(10).reshape(2,5)
a =a.astype(np.int32)
b = np.ones(10).reshape(2,5)
b=b.astype(np.int32)
b

array = np.vstack((a,b))
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [31]:
a = np.arange(10).reshape(2,5)
a =a.astype(np.int32)
b = np.ones(10).reshape(2,5)
b=b.astype(np.int32)
b
array1 = np.hstack((a,b))
array1

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [33]:
arr = np.arange(10).reshape(2,5)
arrflat = arr.flatten()
arrflat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [39]:
array = np.arange(15).reshape(((3,5)))
array1 = array.flatten()
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [46]:
array = np.arange(15)
arr = array.reshape((5,3))
arr


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [50]:
array = np.arange(25).reshape(5,5)
arr = np.square(array)
arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [52]:
array = np.arange(30).reshape(5,6)
arr = np.mean(array)
arr

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [53]:
array = np.arange(30).reshape(5,6)
arr = np.std(array)
arr

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [54]:
array = np.arange(30).reshape(5,6)
arr = np.median(array)
arr

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [55]:
array = np.arange(30).reshape(5,6)
arr = np.transpose(array)
arr

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [58]:
array = np.arange(16).reshape(4,4)
arr = np.trace(array)
arr


30

## Question:13

### Find the determinant of the previous array in Q12?

In [61]:
array = np.arange(16).reshape(4,4)
arr =np.linalg.det(array)
arr

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [62]:
array = np.arange(10)
print("5th percentile of Array is :" , np.percentile(array , 5))
print("95th percentile of Array is :" , np.percentile(array , 95))


5th percentile of Array is : 0.45
95th percentile of Array is : 8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [78]:
empty_array = np.array([])
is_empty = empty_array.size == 0

print("IS ARRAY EMPTY :",is_empty)

IS ARRAY EMPTY : True


#SHAHEER HASAN   # PIAIC86694   
